ruleGroup: segment_ignore
action: ignore
languages:
  - java
rules:
  - id: segment_ignore
    name: Segment Ignore
    regex: ^(?:com.segment.analytics)\.(?:messages.IdentifyMessage|Analytics.builder)