// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateDataSourceInput struct {
	SiloDefinitionID string    `json:"siloDefinitionID"`
	CategoryIDs      []*string `json:"categoryIDs"`
	PurposeIDs       []*string `json:"purposeIDs"`
	Description      *string   `json:"description"`
}

type CreatePropertyInput struct {
	Categories   []string `json:"categories"`
	DataSourceID string   `json:"dataSourceID"`
	Purposes     []string `json:"purposes"`
}

type CreateSiloDefinitionInput struct {
	Description         *string `json:"description"`
	SiloSpecificationID string  `json:"siloSpecificationID"`
	WorkspaceID         string  `json:"workspaceID"`
}

type CreateSiloSpecificationInput struct {
	Name        string  `json:"name"`
	LogoURL     *string `json:"logoURL"`
	DockerImage *string `json:"dockerImage"`
	WorkspaceID string  `json:"workspaceID"`
}

type Property struct {
	ID           string      `json:"id"`
	Categories   []*Category `json:"categories"`
	DataSourceID string      `json:"dataSourceID"`
	Purposes     []*Purpose  `json:"purposes"`
}

type UpdateDataSourceInput struct {
	ID               string   `json:"id"`
	SiloDefinitionID *string  `json:"siloDefinitionID"`
	Categories       []string `json:"categories"`
	Purposes         []string `json:"purposes"`
	Description      *string  `json:"description"`
}

type UpdatePropertyInput struct {
	Categories   []string `json:"categories"`
	DataSourceID *string  `json:"dataSourceID"`
	Purposes     []string `json:"purposes"`
}

type UpdateSiloDefinitionInput struct {
	ID                  string  `json:"id"`
	Description         *string `json:"description"`
	SiloSpecificationID *string `json:"siloSpecificationID"`
}

type UpdateSiloSpecificationInput struct {
	ID          string  `json:"id"`
	DockerImage *string `json:"dockerImage"`
	Schema      *string `json:"schema"`
	Name        *string `json:"name"`
	LogoURL     *string `json:"logoUrl"`
}
