name: Build Core Docker Images

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Core
        run: make docker-build docker-build-codescan
